language: r
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=3.1.0
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
