language: R
sudo: false
cache: packages

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O http://kingaa.github.io/scripts/mac-fortran.sh; sh mac-fortran.sh; rm -f mac-fortran.sh; fi

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
    - os: linux
      env: RVERSION=3.1.2
    - os: linux
      env: RVERSION=release
    - os: linux
      env: RVERSION=devel
    - os: osx
      env: RVERSION=release
    - os: osx
      env: RVERSION=devel
